### ISSUE TITLE
Color display suggestion

### ISSUE THREAD

**Issue by anouvel** [42shTests/logger#3]
Because it is not always clear when there is a lot of debugging messages, we could improve the color display.

Today, we have this situation : 

```
[blue] --------------------- [BLUE] [WHITE] ---------------------------------- [WHITE]
[ 2016/06/16 16:06:53 ] [ INFO    ] (l. 25) parser.c -> parser receives input : "ls"
```

The fact is that when we have an info log and debug log, sometimes, it is hard to understand that we change of logging type. So 2 possibilities : 

```
[blue] ----------------------------------------- [BLUE] [WHITE] ---------- [WHITE]
[ 2016/06/16 16:06:53 ] [ INFO    ] (l. 25) parser.c -> parser receives input : "ls"
```

OR

```
[blue] ---------------------------------------------------------------------- [BLUE]
[ 2016/06/16 16:06:53 ] [ INFO    ] (l. 25) parser.c -> parser receives input : "ls"
```

Personnaly, I vote for the first, we color from begining to the arrow.

Notice that debug and trace still have the same color (eg default shell color, eg2 white or grey).

The actual : 

![now](https://cloud.githubusercontent.com/assets/8018172/16120162/e19f8aae-33de-11e6-843c-37495a9b2879.png)

The new one : 

![new](https://cloud.githubusercontent.com/assets/8018172/16120161/e19e844c-33de-11e6-83c3-6debe0aa2d25.png)

Tell me what you want to do / have :)

**Comment by gabkk** [comment]
i vote for the first one `[blue] ----------------------------------------- [BLUE] [WHITE] ---------- [WHITE]
[ 2016/06/16 16:06:53 ] [ INFO    ] (l. 25) parser.c -> parser receives input : "ls"` 👍

**Comment by mleconte-06** [comment]
i prefer the full color :)

**Comment by jgigault** [comment]
I too prefer the full color :-)

**Comment by abombard** [comment]
i like 2 and 3 !

**Comment by anouvel** [comment]
done for the third one :)
